project_name: lg

release:
  github:
    owner: toskatok
    name: lg

builds:
  - binary: lg
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    goarm:
      - "6"
    main: ./cmd/lg/main.go
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - ./cmd/lg/config.yml # sample configuration file
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
