language: go
go:
- '1.11'
env:
  global:
    secure: RpdM2nM1zPlWFZ1NRW3yCMtDfNMA24SVlLOo0q9jfwW7NptzC9PA/VgltRVZwz5SwNsbXraXxc3NYIilhP8UF8Xn5WyJvMgDwXVpKpB8z2tZ735ivLB72ziXgxg/8I59DHfTiO1BgMHKyWYguFxrzoKvpxMVmqTnmszDrlDCmyyL4srj2QmH8ZQhFQlMJyUg/vbGplfyKD01+jVGvANtZTEWjxIqI53zpRDdkjJNEAkVcHTJzplcmy4CejmrKHvuDY8xvIX7j9SnR4pYBAjrltPe10xrsJl18H4EG4lonnaOcNVX+M9RYwDQ671HSp7kvYPvLY8qbqpK5GpUoUUl/cxLF6boYX/mNWxfTATLpX7u66crQcte4QdzED50+Ah7c/5Jjr6r3X9YTrPTef2r5DnNanjIicbtr+Gt05QmhNDsip/aDvo4TPvBluq0MR8gHWdLPjnJayD8saBwVUIlPzqVZl7NMKHP8rXTsxNZfIE76qtJ5UC8A4yWhVME6k/Ub+c9ekYBmTg8lN7IOS0qUGhHNhXIdLT+bqGdc81DKlRsznLkq2LAh2hrR0B6Hneet6ETq9wZq6Rqz+cw+1RwJCIk7T20s/mvKPdVmeZkzFlbP+L7SgTsqXk/PjkYY25hFmO8u5GgjGNfUttcBkYTeqDeiWY17bYj1UdWq1uTg1c=
before_install:
- GO_FILES=$(find . -iname '*.go' )
- PKGS=$(go list ./... )
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- go get -u golang.org/x/lint/golint
- go get -u github.com/kisielk/errcheck
install:
- dep ensure
script:
- go vet -v $PKGS
- errcheck -verbose $PKGS
- golint -set_exit_status $PKGS
before_deploy:
- git checkout Gopkg.lock
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
