language: go
go:
  - "1.11"

env:
  - GO111MODULE=on
# please note that GITHUB_TOKEN which is required by goreleaser is defined in travis website.

before_install:
  - PKGS=$(go list ./... )             # All the import paths

  # Install linters
  - go get -u golang.org/x/lint/golint              # Linter
  - go get -u github.com/kisielk/errcheck           # errcheck checks that you checked errors.

install:
  - go mod tidy
  - go mod download

script:
  - go vet -v $PKGS                   # go vet is the official Go static analyzer
  - errcheck -verbose $PKGS           # Check for unchecked errors
  - golint -set_exit_status $PKGS     # One last linter

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
