openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/I1820/i1820-lg/1.0.0
info:
  description: Fully customizable MQTT based load generator
  version: "1.0.0"
  title: I1820 Load Generator API
  contact:
    name: Parham Alvani
    email: parham.alvani@gmail.com
  license:
    name: GPL 3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html

tags:
  - name: instances
    description: Manage running instances
paths:
  /instances:
    post:
      tags:
        - instance
      summary: runs new generator instance
      parameters:
        - in: query
          name: destination
          schema:
            type: string
            format: uri
            default: 'mqtt://127.0.0.1:1883'
          description: 'scheme://(host or host:port)'
        - in: query
          name: rate
          schema:
            type: integer
            format: int64
            default: 1
          description: send interval in millisecond
      responses:
        '200':
          description: new instance is up and running
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Config'
        description: Instance configuration
components:
  schemas:
    Config:
      type: object
      properties:
        generator:
          type: object
          properties:
            name:
              type: string
              example: fanco
            info:
              type: object
              example:
                thingID: 5bbd104cefe940cb57dfeb76
        token:
          type: string
          example: 1BLzO2YYB1jH91pRB0cpeIdPMsM
        messages:
          type: array
          items:
            type: object
            additionalProperties: {}
          example:
            - count: "{{.Count}}"
