generator:
  name: isrc
  info:
    devEUI: "0000000000000073"
    applicationID: 10
    applicationName: hello
    deviceName: fake
    gatewayMac: fullyfakemac
messages:
  - 100: 6750
    101: 6606
    lat: 10
    lng: 10
    count: "{{.Count}}"
  - "rand": "{{randn 10}}"
    "time": "{{now}}"
    "count": "{{.Count}}"
  - "100": 7000
    "101": 6606
    "count": "{{.Count}}"
  - "100": 6500
    "101": 6606
    "count": "{{.Count}}"
